feat: Implement static, variable and template catalog field mapping
Multiwoven/multiwoven-server pull request #74
Opened 2024-02-21 10:54 UTC by karthik-sivadas

2024-02-25 19:17 UTC, subintp requested changes

2024-02-25 19:17 UTC, subintp commented on spec/lib/reverse_etl/transformers/user_mapping_spec.rb
> +    context "when using standard, static, and template mapping" do
Duplicate tests ?

2024-02-25 19:17 UTC, subintp commented on spec/lib/reverse_etl/transformers/user_mapping_spec.rb
> +      it "transforms record according to v2 mappings" do
Duplicate tests ?

2024-02-26 08:04 UTC, karthik-sivadas commented on app/interactors/syncs/sync_configurations.rb
> +          value: "{{ 'now' | date: '%Y-%m-%dT%H:%M:%S.%L%z' }}"
This is just a template users can change. This is assigned as a placeholder value which will be placed in the text box which the user can change based on the users need.

2024-02-26 08:05 UTC, karthik-sivadas commented on app/interactors/syncs/sync_configurations.rb
> +          description: "Check input for a RegEx match. Row will be rejected if no match is found",
The current implementation does not, will update accordingly.

2024-02-26 09:25 UTC, karthik-sivadas commented on app/interactors/syncs/sync_configurations.rb
> +          value: "{{ regex_replace : '<[a-zA-Z]>', '<replacement>', '<flags>' }}"
https://javascript.info/regexp-introduction

2024-02-26 09:48 UTC, afthabvp commented on lib/liquid/custom_filters.rb
> +    def regex_test(input, pattern, _replacement = "", flags = "")
regex_test=> choose be the name

2024-02-26 09:52 UTC, afthabvp commented on lib/liquid/custom_filters.rb
> +    def regex_test(input, pattern, _replacement = "", flags = "")
why _replacement?

2024-02-26 10:29 UTC, karthik-sivadas commented on app/interactors/syncs/sync_configurations.rb
> +    def catalog_mapping_types
Done

2024-02-26 10:34 UTC, karthik-sivadas commented on app/models/sync.rb
> +  def stream_name_exists?
done

2024-02-26 10:41 UTC, subintp approved these changes

2024-02-26 10:44 UTC, afthabvp approved these changes

2024-02-26 10:44 UTC, merged