feat: add the aasm sate machine for sync states
Multiwoven/multiwoven-server pull request #84
Opened 2024-02-28 13:15 UTC by afthabvp

## Description

## Related Issue

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would impact existing functionality)
- [ ] Documentation update
- [ ] Chore
  
## How Has This Been Tested?

## Checklist:
- [ ] Ensure a branch name is prefixed with `feature`, `bugfix`, `hotfix`, `release` or `chore` followed by `/` and branch name e.g `feature/add-salesforce-connector`
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-02-29 10:46 UTC, afthabvp commented on app/models/sync_run.rb
> +    event :start do
it should present tense

2024-02-29 14:15 UTC, subintp requested changes

2024-02-29 14:15 UTC, subintp commented on app/models/sync_run.rb
> +      transitions from: :in_progress, to: :paused
What stage pause will be called ?

2024-02-29 14:15 UTC, subintp commented on app/temporal/activities/extractor_activity.rb
> +    def update_failure(sync_run)
move this method to sync_run. Sync should marked as failure whenever we abort the sync run

2024-02-29 14:15 UTC, subintp commented on app/temporal/activities/extractor_activity.rb
> +        raise SyncRunStateExeption,
We need to confirm that the loader and reporter activity will be executed after raising this error. Better to write a test case for this.

2024-02-29 14:15 UTC, subintp commented on app/temporal/activities/extractor_activity.rb
> +        raise SyncRunStateExeption,
Skip the workflow if its is already executed.

2024-02-29 14:15 UTC, subintp commented on app/temporal/activities/reporter_activity.rb
> +    def update_sucess(sync_run)
Move both methods to sync_run. Sync run is best place to own this logic

2024-02-29 14:15 UTC, subintp commented on app/temporal/activities/reporter_activity.rb
> +    def update_failure(sync_run)
Same as above

2024-02-29 14:15 UTC, subintp commented on app/temporal/activities/reporter_activity.rb
> +        raise StandardError,
This should non-retryable error. Nothing can be done if we reach this scenario.

2024-02-29 14:15 UTC, subintp commented on lib/reverse_etl/extractors/incremental_delta.rb
> +        return unless sync_run.may_query?
Log this error and return

2024-02-29 14:15 UTC, subintp commented on lib/reverse_etl/loaders/standard.rb
> +        unless sync_run.may_progress?
Skip the activity. This scenario can happen when a workflow is retried after an error in reporter activity

2024-02-29 14:15 UTC, subintp commented on lib/reverse_etl/loaders/standard.rb
> +      def update_failure(sync_run)
Move this method to sync_run

2024-03-01 04:57 UTC, afthabvp commented on app/temporal/activities/extractor_activity.rb
> +        raise SyncRunStateExeption,
No need exception, we are logging error and skipping

2024-03-01 05:02 UTC, afthabvp commented on app/models/sync_run.rb
> +      transitions from: :started, to: :started
pending => started , actual scenario
started => started,  early failure before moving to querying  and retry
querying => started,  when a retry with error in source query

2024-03-01 05:04 UTC, afthabvp commented on app/controllers/api/v1/sync_runs_controller.rb
> +        sync_runs = current_workspace.syncs.find(params[:sync_id]).sync_runs
different pr

2024-03-01 05:04 UTC, afthabvp commented on app/controllers/api/v1/sync_records_controller.rb
> +        sync_records = current_workspace.syncs.find(params[:sync_id]).sync_runs.find(params[:sync_run_id]).sync_records
different pr

2024-03-01 05:05 UTC, afthabvp commented on app/models/sync.rb
> +    event :complete_successfully do
it should present tense

2024-03-01 05:05 UTC, afthabvp commented on app/models/sync.rb
> +      transitions from: :pending, to: :failed
done

2024-03-01 05:17 UTC, afthabvp commented on app/temporal/activities/extractor_activity.rb
> +    def update_failure(sync_run)
done

2024-03-01 05:18 UTC, afthabvp commented on lib/reverse_etl/loaders/standard.rb
> +      def update_failure(sync_run)
done

2024-03-01 06:25 UTC, karthik-sivadas commented on app/models/sync_run.rb
> +      transitions from: %i[pending started querying], to: :started
Why do we need started state in from transition? And what happens if it's queued? Can't a sync run move from queued state to started? Please write tests for these cases.

2024-03-01 06:27 UTC, subintp commented on app/temporal/activities/extractor_activity.rb
> +      # state of sync run to started only if current stete in [ pending,started,querying]
typo in state

2024-03-01 06:33 UTC, karthik-sivadas commented on app/models/sync_run.rb
> +      transitions from: %i[queued paused in_progress], to: :in_progress
Why are we going from inprogress to inprogress state

2024-03-01 06:34 UTC, karthik-sivadas commented on app/models/sync_run.rb
> +      transitions from: %i[pending started querying queued in_progress paused failed], to: :failed
Same here why are we adding a transitioning state here?

2024-03-01 06:39 UTC, subintp requested changes

2024-03-01 06:39 UTC, subintp commented on app/temporal/activities/reporter_activity.rb
> +    def log_error_and_return(sync_run)
why return in the function name ? This method only logs error

2024-03-01 06:39 UTC, subintp commented on lib/reverse_etl/extractors/incremental_delta.rb
> +        return log_error_and_return(sync_run) unless sync_run.may_query?
return is not needed in the function name ?

2024-03-01 06:39 UTC, subintp commented on lib/reverse_etl/extractors/incremental_delta.rb
> +      def log_error_and_return(sync_run)
why return in the method name ?

2024-03-01 06:39 UTC, subintp commented on lib/reverse_etl/loaders/standard.rb
> +        return log_error_and_return(sync_run) unless sync_run.may_progress?
log_error ?

2024-03-01 06:39 UTC, subintp commented on spec/lib/reverse_etl/loaders/standard_spec.rb
> +    context "when sync run not start" do
Suggestion: "Skip loading when status is corrupted"

2024-03-01 06:39 UTC, subintp commented on spec/lib/reverse_etl/loaders/standard_spec.rb
> +      it "trying to started to in_progrss" do
Test message is not clear. Typo in in_progress

2024-03-01 06:39 UTC, subintp commented on spec/temporal/activities/extractor_activity_spec.rb
> +      sync_run_satrted.reload
typo

2024-03-01 06:39 UTC, subintp commented on spec/temporal/activities/extractor_activity_spec.rb
> +    let(:sync_run_satrted) do
typo in variable naming

2024-03-01 06:42 UTC, subintp requested changes

2024-03-01 06:42 UTC, subintp commented on spec/temporal/activities/extractor_activity_spec.rb
> +    context "when sync run not start" do
context message is not clear. "Skip extraction"

2024-03-01 06:44 UTC, karthik-sivadas commented on app/temporal/activities/extractor_activity.rb
> +    def log_error_and_return(sync_run)
Shouldn't we change the state if it fails?

2024-03-01 06:45 UTC, karthik-sivadas commented on app/temporal/activities/reporter_activity.rb
> +    def log_error_and_return(sync_run)
Same here we need to add state change for failure.

2024-03-01 07:03 UTC, afthabvp commented on app/models/sync_run.rb
> +      transitions from: %i[pending started querying], to: :started
If a temporal activity fails while in the "Started" state, a temporal retry may be initiated. For this retry to occur, the activity transitions from the "Started" state back to "Started," indicating a reattempt of the operation.

2024-03-01 07:09 UTC, afthabvp commented on app/models/sync_run.rb
> +      transitions from: %i[queued paused in_progress], to: :in_progress
same here, we need a transition from in_progress => in_progress for temporal activity retry

2024-03-01 07:10 UTC, afthabvp commented on app/models/sync_run.rb
> +      transitions from: %i[pending started querying queued in_progress paused failed], to: :failed
same here, we need a transition from failed => failed for temporal activity retry

2024-03-01 07:13 UTC, afthabvp commented on app/temporal/activities/extractor_activity.rb
> +    def log_error_and_return(sync_run)
If a sync run fails while in the "Queued" state, with all records present in "SyncRecord," and a retry is initiated from the beginning, Temporal needs to bypass all activities leading up to the "Queued" state during the retry process.

2024-03-01 07:34 UTC, afthabvp commented on spec/temporal/activities/extractor_activity_spec.rb
> +    let(:sync_run_satrted) do
done

2024-03-01 07:34 UTC, afthabvp commented on spec/lib/reverse_etl/loaders/standard_spec.rb
> +      it "trying to started to in_progrss" do
done

2024-03-01 07:34 UTC, afthabvp commented on spec/lib/reverse_etl/loaders/standard_spec.rb
> +    context "when sync run not start" do
done

2024-03-01 07:34 UTC, afthabvp commented on app/temporal/activities/extractor_activity.rb
> +      # state of sync run to started only if current stete in [ pending,started,querying]
done

2024-03-01 07:34 UTC, afthabvp commented on app/temporal/activities/reporter_activity.rb
> +    def log_error_and_return(sync_run)
done

2024-03-01 07:34 UTC, afthabvp commented on lib/reverse_etl/extractors/incremental_delta.rb
> +      def log_error_and_return(sync_run)
done

2024-03-01 07:34 UTC, afthabvp commented on lib/reverse_etl/extractors/incremental_delta.rb
> +        return log_error_and_return(sync_run) unless sync_run.may_query?
done

2024-03-01 07:34 UTC, afthabvp commented on lib/reverse_etl/loaders/standard.rb
> +        return log_error_and_return(sync_run) unless sync_run.may_progress?
done

2024-03-01 11:58 UTC, subintp approved these changes

2024-03-01 11:59 UTC, merged